const express =require('express')
const { liked, comment, checkLikeOrNot, getComments, replyToComment, deleteCommentOrReply, getsinglevideo, getpersonalinfo, getotherpersonalinfo, handlefollowerAndfollowing, getpersonfollow } = require('../controller/FeedbackController')
const checkCookieAuth = require('../middleware/AuthCheck')

const feedbackRouter = express.Router()
feedbackRouter.post('/like',checkCookieAuth,liked)
feedbackRouter.post('/comment',checkCookieAuth,comment)
feedbackRouter.post('/replycomment',checkCookieAuth,replyToComment)
feedbackRouter.post('/deletereplyorcomment',checkCookieAuth,deleteCommentOrReply)
feedbackRouter.post('/handlefollowandfollowing',checkCookieAuth,handlefollowerAndfollowing)
feedbackRouter.post('/getuserfollow',getpersonfollow)
feedbackRouter.get('/islike',checkCookieAuth,checkLikeOrNot)
feedbackRouter.get('/getcomment',getComments)
feedbackRouter.get('/getsinglevideo/:id',getsinglevideo)
feedbackRouter.get('/getpersonaldetail',checkCookieAuth,getpersonalinfo)
feedbackRouter.get('/getotherpersonaldetail',getotherpersonalinfo)
module.exports = feedbackRouter